image:
  repository: ghcr.io/conductionnl/conduction-content-bot
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []

replicaCount: 1

podAnnotations: {}

podSecurityContext:
  runAsUser: 10001
  runAsGroup: 10001
  fsGroup: 10001
  runAsNonRoot: true

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop: ["ALL"]
  seccompProfile:
    type: RuntimeDefault

env: {}
  # Required secrets (set via ArgoCD/ExternalSecrets, don't commit real values):
  # SLACK_APP_TOKEN: xapp-...
  # SLACK_BOT_TOKEN: xoxb-...
  # OPENAI_API_KEY: sk-...

  # Optional tuning (defaults also exist in code; override here if desired)
  OPENAI_MODEL: gpt-5-mini
  OPENAI_TIMEOUT_SECONDS: "30"
  OPENAI_MAX_RETRIES: "5"
  LLM_BACKOFF_BASE_SECONDS: "1.0"
  LLM_BACKOFF_MAX_SECONDS: "15.0"
  HISTORY_MAX_MESSAGES: "10"
  WEBSITE_BASE_URL: https://conduction.nl

  # Currently not used by the code, kept for future compatibility
  MAX_REFERENCE_CHARS: "6000"
  WEB_FETCH_TTL_SECONDS: "1800"

resources: {}
  # limits:
  #   cpu: 500m
  #   memory: 512Mi
  # requests:
  #   cpu: 50m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

networkPolicy:
  enabled: false
  egress:
    ports:
      - port: 443
        protocol: TCP
      - port: 80
        protocol: TCP
    toCIDRs: []

