apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "content-bot.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "content-bot.name" . }}
    helm.sh/chart: {{ include "content-bot.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "content-bot.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "content-bot.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
{{- if .Values.podAnnotations }}
{{ toYaml .Values.podAnnotations | indent 8 }}
{{- end }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- range .Values.imagePullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      securityContext:
{{ toYaml .Values.podSecurityContext | indent 8 }}
      containers:
        - name: content-bot
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
{{ toYaml .Values.securityContext | indent 12 }}
          env:
          {{- range $k, $v := .Values.env }}
            - name: {{ $k }}
              value: "{{ $v }}"
          {{- end }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
              readOnly: false
          resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
        - name: tmp
          emptyDir: {}

