name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      - name: Lint (ruff)
        run: ruff check src

      - name: Format check (black)
        run: black --check src

      - name: Build Docker image
        run: docker build -f dockerfile -t conduction-content-bot:ci .

