name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-lint:
    if: ${{ github.actor != 'github-actions[bot]' && !contains(github.event.head_commit.message, '[skip ci]') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      - name: Lint (ruff)
        run: ruff check src

      - name: Format check (black)
        run: black --check src

      - name: Build Docker image
        run: docker build -f dockerfile -t conduction-content-bot:ci .

  publish:
    needs: build-and-lint
    if: ${{ github.ref == 'refs/heads/main' && github.actor != 'github-actions[bot]' && !contains(github.event.head_commit.message, '[skip ci]') }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
    concurrency:
      group: publish-main
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Compute tags
        id: prep
        shell: bash
        run: |
          SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-7)
          OWNER_LC=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          echo "IMAGE=ghcr.io/${OWNER_LC}/conduction-content-bot" >> $GITHUB_ENV
          echo "TAGS=ghcr.io/${OWNER_LC}/conduction-content-bot:sha-${SHORT_SHA},ghcr.io/${OWNER_LC}/conduction-content-bot:latest" >> $GITHUB_ENV
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: dockerfile
          push: true
          tags: ${{ env.TAGS }}
          labels: org.opencontainers.image.revision=${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Install yq
        shell: bash
        run: |
          sudo curl -L https://github.com/mikefarah/yq/releases/download/v4.44.3/yq_linux_amd64 -o /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq
      - name: Bump Helm image.tag to commit SHA and push to main [skip ci]
        shell: bash
        run: |
          SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-7)
          TAG="sha-${SHORT_SHA}"
          yq -i '.image.tag = strenv(TAG)' charts/content-bot/values.yaml
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add charts/content-bot/values.yaml
          git diff --cached --quiet || git commit -m "chore: bump image tag to ${TAG} [skip ci]"
          git push origin HEAD:main

