name: Conduction Content Bot

on:
  workflow_dispatch:

concurrency:
  group: conduction-content-bot
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Run bot
        env:
          # Required secrets
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SLACK_APP_TOKEN: ${{ secrets.SLACK_APP_TOKEN }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          # Optional repo variables with sane defaults
          OPENAI_MODEL: ${{ vars.OPENAI_MODEL || 'gpt-5-mini' }}
          OPENAI_TIMEOUT_SECONDS: ${{ vars.OPENAI_TIMEOUT_SECONDS || '30' }}
          OPENAI_MAX_RETRIES: ${{ vars.OPENAI_MAX_RETRIES || '3' }}
          LLM_BACKOFF_BASE_SECONDS: ${{ vars.LLM_BACKOFF_BASE_SECONDS || '1.0' }}
          LLM_BACKOFF_MAX_SECONDS: ${{ vars.LLM_BACKOFF_MAX_SECONDS || '15.0' }}
          HISTORY_MAX_MESSAGES: ${{ vars.HISTORY_MAX_MESSAGES || '10' }}
          WEBSITE_BASE_URL: ${{ vars.WEBSITE_BASE_URL || 'https://conduction.nl' }}
        run: |
          python -m conduction_content_bot

